services:
  chatops_app:
    build: .
    container_name: chatops_service
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    working_dir: /app
    restart: unless-stopped
